Address the import error
To address the ImportError: cannot import name 'SparseActivatedMultiheadAttention', we move  'from .sparse_activated_multihead_attention import SparseActivatedMultiheadAttention' from line 31 to line 30, which is before import transformer encoder layer ( in it SparseActivatedMultiheadAttention is called)